# Generated by Django 4.2.1 on 2023-06-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
