# Generated by Django 4.2.1 on 2023-06-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_landingpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingPage',
        ),
    ]
